- platform: template
  sensors:

    smart_irrigation_z01_hourly_netto_precipitation:
      friendly_name: Smart Irrigation Z01 Netto Precipitation (updated hourly)
      value_template: "{{state_attr('sensor.smart_irrigation_z01_hourly_adjusted_run_time','netto_precipitation')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z01_bucket:
      friendly_name: Smart Irrigation Z01 Bucket
      value_template: "{{state_attr('sensor.smart_irrigation_z01_daily_adjusted_run_time','bucket')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z02_hourly_netto_precipitation:
      friendly_name: Smart Irrigation Z02 Netto Precipitation (updated hourly)
      value_template: "{{state_attr('sensor.smart_irrigation_z02_hourly_adjusted_run_time','netto_precipitation')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z02_bucket:
      friendly_name: Smart Irrigation Z02 Bucket
      value_template: "{{state_attr('sensor.smart_irrigation_z02_daily_adjusted_run_time','bucket')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z03_hourly_netto_precipitation:
      friendly_name: Smart Irrigation Z03 Netto Precipitation (updated hourly)
      value_template: "{{state_attr('sensor.smart_irrigation_z03_hourly_adjusted_run_time','netto_precipitation')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z03_bucket:
      friendly_name: Smart Irrigation Z03 Bucket
      value_template: "{{state_attr('sensor.smart_irrigation_z03_daily_adjusted_run_time','bucket')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z04_hourly_netto_precipitation:
      friendly_name: Smart Irrigation Z04 Netto Precipitation (updated hourly)
      value_template: "{{state_attr('sensor.smart_irrigation_z04_hourly_adjusted_run_time','netto_precipitation')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z04_bucket:
      friendly_name: Smart Irrigation Z04 Bucket
      value_template: "{{state_attr('sensor.smart_irrigation_z04_daily_adjusted_run_time','bucket')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z05_hourly_netto_precipitation:
      friendly_name: Smart Irrigation Z05 Netto Precipitation (updated hourly)
      value_template: "{{state_attr('sensor.smart_irrigation_z05_hourly_adjusted_run_time','netto_precipitation')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z05_bucket:
      friendly_name: Smart Irrigation Z05 Bucket
      value_template: "{{state_attr('sensor.smart_irrigation_z05_daily_adjusted_run_time','bucket')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z06_hourly_netto_precipitation:
      friendly_name: Smart Irrigation Z06 Netto Precipitation (updated hourly)
      value_template: "{{state_attr('sensor.smart_irrigation_z06_hourly_adjusted_run_time','netto_precipitation')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z06_bucket:
      friendly_name: Smart Irrigation Z06 Bucket
      value_template: "{{state_attr('sensor.smart_irrigation_z06_daily_adjusted_run_time','bucket')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z07_hourly_netto_precipitation:
      friendly_name: Smart Irrigation Z07 Netto Precipitation (updated hourly)
      value_template: "{{state_attr('sensor.smart_irrigation_z07_hourly_adjusted_run_time','netto_precipitation')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z07_bucket:
      friendly_name: Smart Irrigation Z07 Bucket
      value_template: "{{state_attr('sensor.smart_irrigation_z07_daily_adjusted_run_time','bucket')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z08_hourly_netto_precipitation:
      friendly_name: Smart Irrigation Z08 Netto Precipitation (updated hourly)
      value_template: "{{state_attr('sensor.smart_irrigation_z08_hourly_adjusted_run_time','netto_precipitation')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z08_bucket:
      friendly_name: Smart Irrigation Z08 Bucket
      value_template: "{{state_attr('sensor.smart_irrigation_z08_daily_adjusted_run_time','bucket')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z09_hourly_netto_precipitation:
      friendly_name: Smart Irrigation Z09 Netto Precipitation (updated hourly)
      value_template: "{{state_attr('sensor.smart_irrigation_z09_hourly_adjusted_run_time','netto_precipitation')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z09_bucket:
      friendly_name: Smart Irrigation Z09 Bucket
      value_template: "{{state_attr('sensor.smart_irrigation_z09_daily_adjusted_run_time','bucket')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z10_hourly_netto_precipitation:
      friendly_name: Smart Irrigation Z10 Netto Precipitation (updated hourly)
      value_template: "{{state_attr('sensor.smart_irrigation_z10_hourly_adjusted_run_time','netto_precipitation')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z10_bucket:
      friendly_name: Smart Irrigation Z10 Bucket
      value_template: "{{state_attr('sensor.smart_irrigation_z10_daily_adjusted_run_time','bucket')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z11_hourly_netto_precipitation:
      friendly_name: Smart Irrigation Z11 Netto Precipitation (updated hourly)
      value_template: "{{state_attr('sensor.smart_irrigation_z11_hourly_adjusted_run_time','netto_precipitation')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined

    smart_irrigation_z11_bucket:
      friendly_name: Smart Irrigation Z11 Bucket
      value_template: "{{state_attr('sensor.smart_irrigation_z11_daily_adjusted_run_time','bucket')|float}}"
      icon_template: "mdi:sprinkler-variant"
      unit_of_measurement: inch # mm or inch if you're so inclined
