- platform: template
  sensors:
    sun_elevation:
      friendly_name: Sun Elevation
      unit_of_measurement: °
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    sun_azimuth:
      friendly_name: Sun Azimuth
      unit_of_measurement: °
      value_template: "{{ state_attr('sun.sun', 'azimuth') }}"